-- BANDA PWA v2
-- Запусти целиком в Supabase → SQL Editor.

create table if not exists public.invite_codes(
  code text primary key,
  active boolean not null default true
);

insert into public.invite_codes(code,active)
values ('BANDA2026',true)
on conflict(code) do update set active=excluded.active;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar text not null default '🙂',
  updated_at timestamptz not null default now()
);

create table if not exists public.messages(
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_name text not null,
  sender_avatar text not null default '🙂',
  recipient_id uuid references auth.users(id) on delete cascade,
  kind text not null default 'text' check(kind in ('text','photo','voice')),
  text text not null default '',
  media_url text,
  created_at timestamptz not null default now()
);

alter table public.invite_codes enable row level security;
alter table public.profiles enable row level security;
alter table public.messages enable row level security;

drop policy if exists "invite read" on public.invite_codes;
create policy "invite read" on public.invite_codes for select to authenticated using(active=true);

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select to authenticated using(true);

drop policy if exists "profile own upsert" on public.profiles;
create policy "profile own upsert" on public.profiles for insert to authenticated with check(auth.uid()=id);

drop policy if exists "profile own update" on public.profiles;
create policy "profile own update" on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);

drop policy if exists "messages read" on public.messages;
create policy "messages read" on public.messages for select to authenticated
using(recipient_id is null or sender_id=auth.uid() or recipient_id=auth.uid());

drop policy if exists "messages send" on public.messages;
create policy "messages send" on public.messages for insert to authenticated
with check(sender_id=auth.uid());

insert into storage.buckets(id,name,public)
values('media','media',true)
on conflict(id) do update set public=true;

drop policy if exists "media upload" on storage.objects;
create policy "media upload" on storage.objects for insert to authenticated
with check(bucket_id='media');

drop policy if exists "media read" on storage.objects;
create policy "media read" on storage.objects for select to public
using(bucket_id='media');

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;
